os: linux
dist: trusty
language: python
services: docker

env:
  global:
    - BASE=ams562/desktop:base VERSION=cling


before_script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - docker pull $BASE

script:
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -n $(git log --since $(docker inspect $BASE | grep Created | perl -e "s/.+\"([\d-:T]+).+$/\$1/g" -p)) &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml -e config -e WELCOME)" ]] ||
     (docker build --tag ams562/desktop:$VERSION . &&
      docker push ams562/desktop &&
      touch success)'
  # Test script without launching webbrowser and push new image if successful
  - docker images
